### ISSUE TITLE
Qrypto not able to login in Windows machine

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/qrypto#133]
Jack has reported that users in China are not able to do anything when trying to account login. It just freezes and nothing happens.

Possibly something with the private key hashing logic since thats whats going on in the ss?

```
s.AssertionErroractual: Uint8Array(4) [38, 252, 77, 103]expected: Uint8Array(4) [31, 244, 45, 102]generatedMessage: truemessage: "<Buffer 26 fc 4d 67> deepEqual <Buffer 1f f4 2d 66>"name: "AssertionError"operator: "deepEqual"stack: "AssertionError: <Buffer 26 fc 4d 67> deepEqual <Buffer 1f f4 2d 66>↵    at decryptRaw (chrome-extension://hdmjdgjbehedbnjmljikggbmmbnbmlnd/background.js:54:296452)↵    at Object.decrypt (chrome-extension://hdmjdgjbehedbnjmljikggbmmbnbmlnd/background.js:54:297364)↵    at h.fromEncryptedPrivateKey (chrome-extension://hdmjdgjbehedbnjmljikggbmmbnbmlnd/background.js:54:326430)↵    at c.recoverFromPrivateKeyHash (chrome-extension://hdmjdgjbehedbnjmljikggbmmbnbmlnd/background.js:54:522421)↵    at c.validatePassword (chrome-extension://hdmjdgjbehedbnjmljikggbmmbnbmlnd/background.js:54:519523)↵    at c.login (chrome-extension://hdmjdgjbehedbnjmljikggbmmbnbmlnd/background.js:54:516504)"__proto__: Error
background.js:54 s.AssertionErroractual: Uint8Array(4) [38, 252, 77, 103]expected: Uint8Array(4) [77, 213, 165, 251]generatedMessage: truemessage: "<Buffer 26 fc 4d 67> deepEqual <Buffer 4d d5 a5 fb>"name: "AssertionError"operator: "deepEqual"stack: "AssertionError: <Buffer 26 fc 4d 67> deepEqual <Buffer 4d d5 a5 fb>↵    at decryptRaw (chrome-extension://hdmjdgjbehedbnjmljikggbmmbnbmlnd/background.js:54:296452)↵    at Object.decrypt (chrome-extension://hdmjdgjbehedbnjmljikggbmmbnbmlnd/background.js:54:297364)↵    at h.fromEncryptedPrivateKey (chrome-extension://hdmjdgjbehedbnjmljikggbmmbnbmlnd/background.js:54:326430)↵    at c.recoverFromPrivateKeyHash (chrome-extension://hdmjdgjbehedbnjmljikggbmmbnbmlnd/background.js:54:522421)↵    at c.validatePassword (chrome-extension://hdmjdgjbehedbnjmljikggbmmbnbmlnd/background.js:54:519523)↵    at c.login (chrome-extension://hdmjdgjbehedbnjmljikggbmmbnbmlnd/background.js:54:516504)"__proto__: Error
```

![image](https://user-images.githubusercontent.com/4350404/44197708-9ea43600-a169-11e8-9e94-c58e5ab8f8f2.png)

**Comment by dwalintukan** [comment]
Crashes at the assert here:
https://github.com/bitcoinjs/bip38/blob/master/index.js#L122

Possible idea that Jack might have used a non-UTF8 pw.

**Comment by dwalintukan** [comment]
@soshochang also, concerning this bug. we should also wrap the logic in a try/catch and boot the user back to the last page instead of having them hang on the `Loading Screen`

**Comment by dwalintukan** [comment]
Jack says the bug is resolved. Possible that he had an earlier alpha version and the logic changed causing incompatible data.
